# Debate Mirror MCP Configuration

debate:
  max_turns: 10
  max_time: 1800  # 30 minutes
  turn_timeout: 120  # 2 minutes per turn

agents:
  pro:
    model: "gemini-2.0-flash-exp"
    provider: "google"
    temperature: 0.7
    max_tokens: 1000
  
  con:
    model: "gemini-2.0-flash-exp"
    provider: "google"
    temperature: 0.7
    max_tokens: 1000
  
  judge:
    model: "gemini-2.0-flash-exp"
    provider: "google"
    temperature: 0.3
    max_tokens: 1500

tools:
  web_search:
    provider: "duckduckgo"  # Options: duckduckgo, tavily, serpapi
    max_results: 5
    timeout: 30

# API keys (can be overridden by environment variables)
api_keys:
  google_api_key: "AIzaSyAGCgJRasGcdY2k0LZqNSm-Sr3Kzktk2N4"
  openai_api_key: ""
  anthropic_api_key: ""
  xai_api_key: ""
  groq_api_key: ""
  tavily_api_key: ""
  serpapi_key: ""
